seed: 0
experiment:
  eval_path: data/era5_eval_5p6.zarr
  climatology_path: data/clim_wb2_5p6.zarr
  name: pyramid
dataset:
  path: data/era5_5p6.zarr
  stats_path: data/stats_train.zarr
  variables:
  - T2M
  - Z850
  - Z500
  - Z250
  - T850
  - T500
  - T250
  - Q850
  - Q500
  - Q250
  - U850
  - U500
  - U250
  - V850
  - V500
  - V250
  - TP6h
  sequence_length: 2
  time_slice:
    start: '2009'
    stop: '2015'
  lat_slice: null
  lon_slice: null
network:
  name: vit
  dim: 128
  num_layers: 4
  num_heads: 4
  dim_heads: 32
  patch_size:
  - 4
  - 4
  patch_sizes: null
  expansion_factor: 2
  drop_path: 0.0
  residual: true
objective:
  name: pyramid_mse
  weights: null
  kwargs:
    levels: 3
    weights:
    - 4.0
    - 2.0
    - 1.0
trainer:
  lr: 0.001
  weight_decay: 0.01
  betas:
  - 0.9
  - 0.95
  batch_size: 16
  num_workers: 0
  max_steps: 2000
  schedulers:
  - type: linear
    steps: 100
    start_factor: 0.01
  - type: cosine
    steps: 1900
  rollout_steps: 4
  train_rollout_steps: 1
  pre_steps: 0
  val_time_slice: null
  val_stride: 40
  predict_steps: 20
  predict_stride: 5
world: null
