"""Assemble paper/overleaf/ and paper/overleaf_upload.zip for upload to Overleaf.

Copies the TCCML style file, the bibliography and the current figures, and extracts the code
listings for Appendix A straight from utils/, so the listings always match the code that ran.
main.tex is only written if it does not exist yet, so rerunning never overwrites your writing.

    python paper/build_overleaf.py
"""
import ast
import re
import shutil
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "paper" / "overleaf"
FIGURES = ["F1_rmse_z500_t850.pdf", "E1_spectrum_ratio.pdf", "E2_rmse_change_heatmap.pdf"]
LISTINGS = [  # (file, definition name, caption)
    ("utils/components.py", "SeamSmoother", "Seam smoother: a 3$\\times$3 convolution on the output field, periodic in longitude, initialised as the identity."),
    ("utils/components.py", "MultiScaleViT", "Multi-scale embedding (A): tokens at several patch sizes share attention; the per-scale read-outs are summed."),
    ("utils/loss_fn.py", "laplacian_pyramid", "Scale decomposition used by the pyramid loss."),
    ("utils/loss_fn.py", "f_pyramid_mse", "Pyramid loss (C, C$'$): squared error per scale band, weighted and expanded back to the grid."),
]


def source_without_docstrings(path: Path, name: str) -> str:
    text = path.read_text()
    tree = ast.parse(text)
    node = next(n for n in ast.walk(tree) if isinstance(n, (ast.ClassDef, ast.FunctionDef)) and n.name == name)
    lines = text.splitlines()
    segment = lines[node.lineno - 1: node.end_lineno]
    drop = set()
    for n in ast.walk(node):
        if isinstance(n, (ast.ClassDef, ast.FunctionDef)) and n.body and isinstance(n.body[0], ast.Expr) \
                and isinstance(getattr(n.body[0], "value", None), ast.Constant) and isinstance(n.body[0].value.value, str):
            doc = n.body[0]
            drop.update(range(doc.lineno - node.lineno, doc.end_lineno - node.lineno + 1))
    kept = [line for i, line in enumerate(segment) if i not in drop and not re.match(r"^\s*#", line)]
    return "\n".join(line.split("  #")[0].rstrip() for line in kept)


def main() -> None:
    (OUT / "figures").mkdir(parents=True, exist_ok=True)
    shutil.copy(ROOT / "paper" / "template" / "tackling_climate_workshop_style.sty", OUT)
    shutil.copy(ROOT / "explore" / "references.bib", OUT / "references.bib")
    for fig in FIGURES:
        shutil.copy(ROOT / "explore" / "figures" / fig, OUT / "figures" / fig)

    blocks = []
    for file, name, caption in LISTINGS:
        code = source_without_docstrings(ROOT / file, name)
        blocks.append(f"\\begin{{lstlisting}}[caption={{{caption} From \\texttt{{{file.replace('_', chr(92) + '_')}}}.}}]\n{code}\n\\end{{lstlisting}}\n")
    (OUT / "appendix_code.tex").write_text("% generated by paper/build_overleaf.py from utils/ -- do not edit by hand\n\n" + "\n".join(blocks))

    main_tex = OUT / "main.tex"
    if not main_tex.exists():
        shutil.copy(ROOT / "paper" / "main_skeleton.tex", main_tex)

    zip_path = ROOT / "paper" / "overleaf_upload.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for f in sorted(OUT.rglob("*")):
            if f.is_file():
                z.write(f, f.relative_to(OUT))
    print(f"wrote {OUT} and {zip_path}")
    for f in sorted(OUT.rglob("*")):
        if f.is_file():
            print(f"  {f.relative_to(OUT)}  ({f.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
